### ISSUE TITLE
session plugins has encounter some question.

### ISSUE THREAD

**Issue by 13233032535** [Kong/kong-plugin-session#24]
The request termination plugin always has a primary key that cannot reference consumption when configuring the ID of anonymous users..

what shoud i do?

Looking forward to your recovery as soon as possible,thanks!!
@kidd @kikito @ikeike443 @nijikokun @eskerda

**Comment by kikito** [comment]
Hello, it is a bit difficult to understand what your problem is here.

I have deduced so far that you are following the steps on this plugin's README and you are having trouble at some point with the anonymous user. Kindly provide us with the following information:

* The version of Kong are you using

* The **step number** in the README where you are having trouble (4, 6, 8, or some other step?)

* **What you expected to happen at that step, and what happened instead **? Please add as much detail on this one. Exact error messages (or logs, if you have them) might help.
